baseURL      = "https://lulukodesu.github.io/my-blog"
languageCode = "zh-cn"
title        = "ruruko"

# Theme i18n support
# See i18n folder for available languages
defaultContentLanguage = "zh-cn"

# Set hasCJKLanguage to true if DefaultContentLanguage is a CJK language
# This will make .Summary and .WordCount behave correctly
hasCJKLanguage = false

[[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v3"

[pagination]
    pagerSize = 4

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[services.disqus]
    shortname = "rurukodesu"

[caches]
  [caches.images]
    dir = ':cacheDir/images'